# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["web/node_modules", "web/build", "web/dist", "tmp", "vendor"]
exclude_file = []
exclude_regex = []
follow_symlink = false

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta" 